{% set name = "distmetrics" %}
{% set version = "1.0.8" %}
{% set python_min = "3.12" %} 

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/53/65/757c4e73e6031aab346dce77444cedc123959b70cef6a3b16780fc60c5a4/distmetrics-{{ version }}.tar.gz
  sha256: a3c84741ed6e5f2595a068c3e057b121d2cd17fe3dc409fb7656663abc41fd08

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - affine
    - rasterio
    - numpy
    - dem_stitcher
    - scikit-image
    - matplotlib-base
    - scipy
    - pydantic
    - astropy-base
    - einops
    - tenacity
    - asf_search
    - shapely
    - geopandas
    - pytorch
    - pydantic
    - asf_search
    - tqdm
    - pandas

test:
  imports:
    - distmetrics
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/opera-adt/distmetrics
  summary: Measure Disturbances in OPERA RTC-S1 Stacks
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - richw7185
    - cmarshak
    - taliboliver
